from openai.types.responses import (
    Response,
    ResponseOutputMessage,
    ResponseOutputText,
    Reasoning,
    ResponseTextConfig,
    ResponseFormatText,
    ResponseUsage,
    InputTokensDetails,
    OutputTokensDetails,
)

Response(
    id="resp_09c58d643278889b006919250fde48819294b719c14e8a2870",
    created_at=1763255567.0,
    error=None,
    incomplete_details=None,
    instructions=None,
    metadata={},
    model="gpt-4o-mini-2024-07-18",
    object="response",
    output=[
        ResponseFunctionToolCall(
            arguments='{"name":"Hary"}',
            call_id="call_5uKG4zDKyNb1m58abnTjJYem",
            name="glaze_tool",
            type="function_call",
            id="fc_09c58d643278889b00691925110e408192945194456a039be5",
            status="completed",
        )
    ],
    parallel_tool_calls=True,
    temperature=1.0,
    tool_choice="auto",
    tools=[
        FunctionTool(
            name="glaze_tool",
            parameters={
                "type": "object",
                "properties": {"name": {"type": "string"}},
                "additionalProperties": False,
                "required": ["name"],
            },
            strict=True,
            type="function",
            description="If the prompt describes someone who is awesome, return the name of the person.",
        )
    ],
    top_p=1.0,
    background=False,
    conversation=None,
    max_output_tokens=None,
    max_tool_calls=None,
    previous_response_id=None,
    prompt=None,
    prompt_cache_key=None,
    reasoning=Reasoning(effort=None, generate_summary=None, summary=None),
    safety_identifier=None,
    service_tier="default",
    status="completed",
    text=ResponseTextConfig(format=ResponseFormatText(type="text"), verbosity="medium"),
    top_logprobs=0,
    truncation="disabled",
    usage=ResponseUsage(
        input_tokens=87,
        input_tokens_details=InputTokensDetails(cached_tokens=0),
        output_tokens=17,
        output_tokens_details=OutputTokensDetails(reasoning_tokens=0),
        total_tokens=104,
    ),
    user=None,
    billing={"payer": "developer"},
    prompt_cache_retention=None,
    store=True,
)
